Fixed DeletePropertyController.java - getting localname of property properly
vivo-project/Vitro pull request #200
Opened 2021-01-26 13:05 UTC by matthiasluehr

**[JIRA Issue] https://jira.lyrasis.org/browse/VIVO-1816

# What does this pull request do?
Fixed the way the localname of a property is determined by DeletePropertyController.java

2021-01-26 13:06 UTC, matthiasluehr commented
Supersedes https://github.com/vivo-project/VIVO/pull/202

2021-01-26 22:22 UTC, awoods requested changes

2021-01-26 22:22 UTC, awoods commented on api/src/main/java/edu/cornell/mannlib/vitro/webapp/controller/freemarker/DeletePropertyController.java
> +		Property prop = ResourceFactory.createProperty(predicateUri);
Nice job, @matthiasluehr .

If you could fix the formatting to align with the lines before and after, we can get this merged.

2021-01-27 13:18 UTC, matthiasluehr commented
vim fixed it (hopefully). I blame it on Visual Studio Code.

2021-01-27 23:09 UTC, awoods approved these changes

2021-01-27 23:13 UTC, merged