Renamed customAction to customRestAction
vivo-project/Vitro pull request #258
Opened 2022-02-21 15:07 UTC by litvinovg

Renamed customAction to customRestAction, used by Resources to avoid ambiguity.
# Interested parties
Tag (@ mention) interested parties or, if unsure, @VIVO-project/vivo-committers

2022-02-21 15:16 UTC, chenejac requested changes
I suggest to uppercase rest (to be REST). What do you think?

2022-02-22 08:09 UTC, litvinovg commented
> I suggest to uppercase rest (to be REST). What do you think?
Sure, I will fix that

2022-02-22 08:34 UTC, chenejac approved these changes

2022-02-22 14:12 UTC, wwelling approved these changes

2022-02-22 21:24 UTC, merged