fix: process string and untyped literals differently
vivo-project/Vitro pull request #296
Opened 2022-06-02 13:58 UTC by litvinovg

Fixes for https://github.com/vivo-project/VIVO/issues/3717

2022-06-06 12:59 UTC, wwelling commented on api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/VTwo/MultiValueEditSubmission.java
> -			} else if ( XSD.xstring.getURI().equals(datatypeUri) || RDF.dtLangString.getURI().equals(datatypeUri) ){
Hi @litvinovg, could you help me understand why `XSD.xstring.getURI()` is no longer a valid condition here and below?

2022-06-06 13:01 UTC, wwelling commented on api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/VTwo/MultiValueEditSubmission.java
> +				if( lang != null && lang.length() > 0 )	{
As we are here, this would be better using `StringUtils` as done below. `StringUtils.isNotEmpty(lang)`

2022-06-06 13:03 UTC, wwelling commented on api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/VTwo/MultiValueEditSubmission.java
> +        return !StringUtils.isBlank(literal.getLanguage());
`StringUtils.isBlank` will return true for and whitespace character. That will likely cause an issue the same as an empty string. Additionally, I would recommend the negation StringUtils method `isNotEmpty`

2022-06-06 13:05 UTC, wwelling commented on api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/VTwo/MultiValueEditSubmission.java
> +        if (labelLiterals.size() == 0) {
Aside: I am not a fan of all this uncertainty in code. Would be to be certain an empty list was not added to the map, would be nice to be certain a null was not added to said list, etc.

With that said, shouldn't we check to see if the list in the map is not null?

2022-06-06 15:09 UTC, wwelling submitted a review, later dismissed
Code review looks good.

2022-06-30 23:36 UTC, gneissone requested changes
I'm experiencing different behaviors when editing via the front end editor form vs the 'Edit this individual' button

Initial value after creating new faculty member
![Screen Shot 2022-06-30 at 5 27 16 PM](https://user-images.githubusercontent.com/10748475/176794963-5aeb89a1-c3cc-4cd7-b907-bf8c0b590ab9.png)

Edit via front end....
![Screen Shot 2022-06-30 at 5 30 48 PM](https://user-images.githubusercontent.com/10748475/176795109-5b520742-7001-4810-a2fd-e9aa3384c7a9.png)

Keeps language tags. I believe this is the intended behavior. 
![Screen Shot 2022-06-30 at 5 31 30 PM](https://user-images.githubusercontent.com/10748475/176795131-946449f2-92d2-4675-aa3e-418ad2fe2923.png)

Edit via 'edit this individual'...
![Screen Shot 2022-06-30 at 5 28 08 PM](https://user-images.githubusercontent.com/10748475/176795169-2c0b509f-1d61-44d8-80f7-fd9c3ff3abe7.png)

Language tags gone
![Screen Shot 2022-06-30 at 5 28 21 PM](https://user-images.githubusercontent.com/10748475/176795181-2ef378c5-f185-458c-8ce6-9b7a211b5ad9.png)

Can similar fixes be applied to EntityRetryController.java so it behaves in the same way?

2022-07-01 15:51 UTC, gneissone commented
Okay, at the very least we can document the incongruity. Perhaps for now we can add a disclaimer to the backend editing form alerting the user that the form will remove language tags (only if multilanguage is enabled?? or always??)

2022-07-01 17:14 UTC, gneissone approved these changes
Works as expected. To mitigate the issue described in my previous review I would like to see https://github.com/vivo-project/Vitro/pull/313 merged.

2022-07-03 19:34 UTC, chenejac approved these changes

2022-07-04 20:10 UTC, merged