Create initial Login controller with tests
vivo-project/Vitro pull request #299
Opened 2022-06-07 19:42 UTC by VeljkoMaksimovic

Created initial Login controller that uses already existing Authorization module for authenticating users, and later saving them to a session

2022-06-08 14:27 UTC, wwelling requested changes
Could we assert the existence on the session cookie on successful login response? There are also a few formatting fixes that can be made with missing spaces between method and starting code block bracket. Otherwise, this looks good.

2022-06-08 21:38 UTC, wwelling commented
@VeljkoMaksimovic looks like I asked for something that existing testing strategy doesn't afford, https://github.com/vivo-project/Vitro/blob/4ed88b81e3738fccbf3beef677bc165bcaa37179/api/src/test/java/stubs/javax/servlet/http/HttpServletResponseStub.java#L250. Honestly, I think we should avoid using these existing stubs and mock the response the same as the request and verify appropriate method calls are made on the response.

However, the concern I have is how the browser will provide session in subsequent requests after log in. I was assuming this would be done by a session cookie on the response to login. Yet it does not appear the login process tested calls add cookie.

2022-06-08 21:49 UTC, wwelling commented on api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/authentication/LoginController.java
> +@WebServlet(name = "Login", urlPatterns = {"/rest_login"})
Can we follow the existing dynamic API request paths?

https://github.com/vivo-project/Vitro/blob/sprint-dynapi-2022-feb-staging/api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/RESTEndpoint.java#L27

I would suggest `/api/login` and possibly create constant such as https://github.com/vivo-project/Vitro/blob/sprint-dynapi-2022-feb-staging/api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/request/ApiRequestPath.java#L15

```
API_SERVLET_PATH + "/login";
```

2022-06-08 21:53 UTC, wwelling commented
@VeljkoMaksimovic tested the login via postman and it does indeed create the session cookie. It does it via Set-Cookie header. Can you add assertion in the login test that the response does indeed have the Set-Cookie header? And please consider switching to a mock response opposed to using existing Vitro stubs.

![image](https://user-images.githubusercontent.com/8352733/172723883-2c7af334-8332-4cda-8808-04ff145f536c.png)

2022-06-08 22:07 UTC, wwelling commented on api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/authentication/LoginController.java
> +            response.sendError(HttpServletResponse.SC_BAD_REQUEST, message);
We should provide 401 for when authentication fails but the request is valid. https://www.rfc-editor.org/rfc/rfc7235#section-3.1

If missing username or password parameters 400 is valid.

2022-06-08 22:10 UTC, wwelling commented
Sorry I missed a few points on first review.

2022-06-09 22:15 UTC, VeljkoMaksimovic commented
> @VeljkoMaksimovic tested the login via postman and it does indeed create the session cookie. It does it via Set-Cookie header. Can you add assertion in the login test that the response does indeed have the Set-Cookie header? And please consider switching to a mock response opposed to using existing Vitro stubs.
> 
> ![image](https://user-images.githubusercontent.com/8352733/172723883-2c7af334-8332-4cda-8808-04ff145f536c.png)
> 
> ![image](https://user-images.githubusercontent.com/8352733/172724085-fac9cd61-62dd-4e46-a6c6-c3d6bdcaa220.png)

Not sure I can check whether response has a Set-Cookie header since response is a mock. I thought to verify whether response.setHeader(eq("Set-Cookie",any(String.class)) was called exactly once, but that can't be done inside the unit test since session header is not added inside the LoginController.doPost or .process() methods, but later in the chain of executed functions. All I could check is whether the ".getSession" and .setAttribute("logged_in_user") method were called

2022-06-09 22:26 UTC, VeljkoMaksimovic commented
> Sorry I missed a few points on first review.

no problem

2022-06-09 23:37 UTC, wwelling commented
Will need an integration test for the endpoint.

2022-06-09 23:39 UTC, wwelling commented on api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/authentication/LoginController.java
>      private static final Log log = LogFactory.getLog(RESTEndpoint.class);
Logger is not used. Is also for wrong class.

2022-06-09 23:46 UTC, wwelling approved these changes
Please remove logger or update its class.

I think it may be too much to ask for integration tests for the existing Vitro authenticator. That being the only way to really assert client will be logged in, we will have to settle for manual testing until strategy for login controller integration tests is derived.

2022-06-10 12:59 UTC, SoulsMark approved these changes

2022-06-10 13:11 UTC, merged