N3 operation retractions
vivo-project/Vitro pull request #305
Opened 2022-06-10 19:12 UTC by VeljkoMaksimovic

Extended N3TemplateOperation (both definition and implementation) to also support retraction of triplets.

Question
How to delete multiple entries with one n3 triplet? For example, delete all statements that start with <http://Joe> <http://Has>

2022-06-11 10:26 UTC, chenejac commented
> For now, both n3TextAdditions and n3TextRetraction property cardinalities are set to min:0, max:1. That allows to have n3Template that has no addition statements, nor retraction statements, which should not be valid. Not sure how to set "collective cardinality" on those two properties to be min:1

Probably this is a task for me to be resolved by definition of a SHACL rule.

2022-06-14 08:22 UTC, litvinovg commented
I think we need integration tests to check that action with n3 template is converted into java action with configurationBeanLoader and instantiated action with n3 template can process operation data.

2022-06-14 09:32 UTC, litvinovg requested changes
It makes sense to rename n3Template to N3Template in ontology as you fixing this.

2022-06-14 09:32 UTC, litvinovg commented on api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components/N3Template.java
> +	private String n3TextAdditions;
Maybe initialize empty string to get rid of null checks?

2022-06-14 09:32 UTC, litvinovg commented on api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components/N3Template.java
> +			if (this.n3TextAdditions != null) substitutedN3AdditionsTemplate=insertParameters(input, this.n3TextAdditions);
I would suggest to always use curly braces

2022-06-14 09:32 UTC, litvinovg commented on api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components/N3Template.java
>  			log.error(e);
I would suggest log.error(e,e);

2022-06-14 09:32 UTC, litvinovg commented on api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components/N3Template.java
> +				additionModels = ProcessRdfForm.parseN3ToRDF(Arrays.asList(substitutedN3AdditionsTemplate), ProcessRdfForm.N3ParseType.REQUIRED);
curly braces

2022-06-14 11:17 UTC, brianjlowe commented
Agree with all of Georgy's requested changes.  In addition, watch line length.  I usually try to not to exceed 80 characters (which may be more conservative than necessary), but as it currently some of the lines needing curly braces overflow the div and are hidden when using Github's Show File view.  This suggests that they are simply too long.

When Georgy's satisfied with the changes, I can add my second approval.  While I don't fully understand the context or use cases, in isolation the approach of adding a retractions template and processing it via the same mechanism as additions seems logical enough.

2022-06-14 11:31 UTC, VeljkoMaksimovic commented
> Agree with all of Georgy's requested changes. In addition, watch line length. I usually try to not to exceed 80 characters (which may be more conservative than necessary), but currently some of the lines needing curly braces overflow the div and are hidden when using Github's Show File view. This suggests that they are simply too long.
> 
> When Georgy's satisfied with the changes, I can add my second approval. While I don't fully understand the context or use cases, in isolation the approach of adding a retractions template and processing it via the same mechanism as additions seems logical enough.

Ok, thanks for the suggestion, will do later in the day

2022-06-14 20:21 UTC, litvinovg requested changes

2022-06-14 20:21 UTC, litvinovg commented on api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components/N3Template.java
> +			n3TextAdditions = substitutedN3AdditionsTemplate=insertParameters(input, n3TextAdditions);
formatting + n3TextAdditions shouldn't be changed during execution.

2022-06-14 20:21 UTC, litvinovg commented on api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components/N3Template.java
> +			n3TextRetractions = substitutedN3RetractionsTemplate=insertParameters(input, n3TextRetractions);
formatting + n3TextRetractions shouldn't be changed during execution.

2022-06-14 20:36 UTC, litvinovg commented
Please add test to verify that after one run of n3template with input data second run with different input data produces different results.

2022-06-14 22:06 UTC, VeljkoMaksimovic commented
> Please add test to verify that after one run of n3template with input data second run with different input data produces different results.

Ok, I added one extra test that does that.

2022-06-15 06:33 UTC, litvinovg commented on api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components/N3Template.java
> +		List<Model> additionModels, retractionModels;
Please declare variables on separate lines

2022-06-15 09:43 UTC, litvinovg approved these changes
Looks good to me.

2022-06-15 12:31 UTC, brianjlowe approved these changes

2022-06-15 12:33 UTC, merged