Dynapi parameters, io re-engineering
vivo-project/Vitro pull request #319
Opened 2022-07-20 16:31 UTC by litvinovg

# What does this pull request do?
* Align dynamic API ontology class names with convention
* Convert dynamic API ontology to n3
* renamed DefaultAction into NullAction
* Re-engineering of OperationData and Converters in progress
* Use jsonPath to load data from requests
* Use json schema validation to validate input and output json.

# What's new?
Classes:
DataStore to replace OperationData
RawData to replace Data

2022-08-22 13:14 UTC, chenejac requested changes
@litvinovg I have reviewed your PR, it looks very well. I have provided a couple of comments. Moreover, the list of classes in the data.types package is a little bit strange, maybe that should be split into two packages.

2022-08-22 13:14 UTC, chenejac commented
> * Parameter can be declared as local. Local parameters are auto-created by api before processing input data.

Is this idea for InternalParameters?

2022-08-22 13:51 UTC, litvinovg commented on home/src/main/resources/rdf/tbox/filegraph/vitro-dynamic-api.n3
> +            rdfs:label "is internal parameter type"@en-US
fixed

2022-08-22 14:02 UTC, litvinovg commented on api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/ActionPool.java
> +    public static ContextModelAccess getModelAccess() {
Should be removed

2022-08-22 14:02 UTC, litvinovg commented on api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/DynamicAPIDocumentation.java
> +            SerializationType parameterType = parameter.getType().getSerializationType();
Ok.

2022-08-22 14:05 UTC, litvinovg commented on api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components/Action.java
> +    }
Parameters not required in request, but created for each action. VIVO models is one of such examples

2022-08-22 14:05 UTC, litvinovg commented on api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components/N3Template.java
> +	@Property(uri = "https://vivoweb.org/ontology/vitro-dynamic-api#hasModel", minOccurs = 1, maxOccurs = 1)
Yes

2022-08-22 14:06 UTC, litvinovg commented on api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components/N3Template.java
> +	public void setN3Template(String n3TextAdditions) {
A mistake,  should be fixed.

2022-08-22 14:06 UTC, litvinovg commented on api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components/Operation.java
>  }
Ok

2022-08-22 14:08 UTC, litvinovg commented on api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components/Parameter.java
> +	private String name;
Ok

2022-08-22 14:11 UTC, litvinovg commented on api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/data/View.java
> +public interface View {
I don't think it is possible. I think that interface should be removed.

2022-08-22 14:11 UTC, litvinovg commented on api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/data/SimpleDataView.java
> +public class SimpleDataView {
No, interface wasn't used. Should be removed.

2022-08-22 14:20 UTC, litvinovg commented on api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components/validators/IsInteger.java
> +				if (!isInteger(data.getJsonValue())) {
Not really. It is serialized value, I will rename the method. It is also a json representation. So the validator always work with Strings.
Still we will need data specific validators to be applied only to specific data types. That should be resolved in future.

2022-08-22 14:21 UTC, litvinovg commented on api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/components/serialization/JsonObjectSerializationType.java
> +public class JsonObjectSerializationType extends SerializationType {
It represents tree structures. So it should be separate, but maybe renamed in future.

2022-08-22 14:31 UTC, litvinovg commented
> > * Parameter can be declared as local. Local parameters are auto-created by api before processing input data.
> 
> Is this idea for InternalParameters?
Yes

2022-08-22 17:12 UTC, litvinovg commented
> @litvinovg I have reviewed your PR, it looks very well. I have provided a couple of comments. Moreover, the list of classes in the data.types package is a little bit strange, maybe that should be split into two packages.

Yes. I split that files into two packages.

2022-08-23 11:54 UTC, chenejac approved these changes
It looks ok for me now. I still don't like the name JsonObjectSerializationType, but we can consider renaming that later.

2022-08-23 12:19 UTC, merged