VIVO 3821: Add configuration to disable or enable Map of Science visualization.
vivo-project/Vitro pull request #373
Opened 2023-02-27 15:35 UTC by kaladay

**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues)**: [3821](https://github.com/vivo-project/VIVO/issues/3821)

Other Relevant Links (Mailing list discussion, related pull requests, etc.)
- For [Vivo PR 3841](https://github.com/vivo-project/VIVO/pull/3841)

# What does this pull request do?
Add an option to not show (disable) Map of Science Visualization link in the same manner as done with the Temporal Visualization link.

This is the Vitro part that adds the required variable to the theme builder code.

# What's new?
A new runtime property `visualization.mapOfScience` is added with the default set to `disabled`.

# How should this be tested?
Change the setting to enabled and disabled and check each theme to confirm behavior is consistent.

# Additional Notes:
I noticed that the Temporal Visualization setting is not applied in Vitro as it is done in Vivo. I added the Map of Science Visualization in the Vitro runtime configuration just like I did for the Vivo runtime configuration. This request is not about applying Temporal Visualization changes and so I left alone the (lack thereof) Temporal Visualization runtime configuration.

# Interested parties
@VIVO-project/vivo-committers

2023-02-27 15:43 UTC, wwelling submitted a review, later dismissed
LGTM. Only question I have is whether to enable by default?

2023-02-27 17:08 UTC, wwelling approved these changes

2023-02-28 09:49 UTC, chenejac requested changes
I have posted one comment which we might discussed before merging this PR.

2023-02-28 09:49 UTC, chenejac commented on home/src/main/resources/config/example.runtime.properties
> +
I think mapOfScience can't work in Vitro, therefore not sure there is a sense in this configuration in example.runtime.properties in Vitro project, I think we need that only in VIVO project (similar as visualization. temporal which I believe is only defined in VIVO runtime.properties). Later, in a separate issue, I hope we might even move the code from Vitro IndividualResponseBuilder to the VIVO codebase.

2023-02-28 14:12 UTC, chenejac approved these changes

2023-02-28 14:13 UTC, merged