Json container array integer
vivo-project/Vitro pull request #406
Opened 2023-06-20 15:19 UTC by litvinovg

**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues/3890)**

# What does this pull request do?
Added integer literal parameter configuration to collect sparql select results in json container array.
Extended error log in ImplementationType class.

# Note

@ivanmrsulja use JsonContainerArray instead of JsonContainer in your use case.

# Interested parties
Tag (@ mention) interested parties or, if unsure, @VIVO-project/vivo-committers

2023-06-20 15:30 UTC, chenejac requested changes
@litvinovg please fix an indentation (layout) issue before we merge this into the dynapi branch

2023-06-20 15:30 UTC, chenejac commented on api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/data/types/implementation/IntegerLiteralParam.java
> +			this.setType(type);
please correct indentation

2023-06-20 18:47 UTC, litvinovg commented on api/src/main/java/edu/cornell/mannlib/vitro/webapp/dynapi/data/types/implementation/IntegerLiteralParam.java
> +			this.setType(type);
done

2023-06-26 07:56 UTC, chenejac approved these changes
@litvinovg well done

2023-06-26 07:56 UTC, merged