Converted hard-coded search results sort option "by relevance" to configuration individual.
vivo-project/Vitro pull request #431
Opened 2023-12-14 09:13 UTC by litvinovg

# What does this pull request do?
Converted hard-coded search results sort option "by relevance" to configuration individual.
Without that there is no way to change order of sort options on search results page.

# Interested parties
@VIVO-project/vivo-committers

2023-12-15 13:44 UTC, chenejac requested changes
@litvinovg thanks for this. Couple of comments:

- when I am entering search page (from the home page, type some text and hit the button Search), the list of results is shown, it is ordered by relevance, but in the dropdown list it is "Sort by" (not "Sort by Relevance")
- should we make labels for other languages ? Meaning to create search_individuals_vitro.n3 and vitro_extended_search.ttl for other languages (with google translations for the beginning)
-  also, we need a strategy when new set labels are grouped in a new file (vitro_extended_search.ttl), and when it is just added in vitro_UiLabel.ttl

2023-12-15 16:28 UTC, litvinovg commented
> @litvinovg thanks for this. Couple of comments:
> 
>     * when I am entering search page (from the home page, type some text and hit the button Search), the list of results is shown, it is ordered by relevance, but in the dropdown list it is "Sort by" (not "Sort by Relevance")
Yes. "Sort by" is a label for the field, not a selected value. Sorting option that was used doesn't present as chosen in the list of sorting options. Until sorting option explicitly selected sorting type is decided by contents of search query: if any text provided, then sort by relevance; if no text was provided, then search by first sort option defined by the used. If sort option wasn't set explicitly it is not saved for the user to avoid situation when at first user selected some filters, got results sorted by first defined sorting option and sorting option is saved and then added some text. In that case sorting option saved on previous step would prevent user from getting results based on scores calculated from text query.
>     * should we make labels for other languages ? Meaning to create search_individuals_vitro.n3 and vitro_extended_search.ttl for other languages (with google translations for the beginning)
Yes.

2023-12-15 17:38 UTC, litvinovg commented
@chenejac Added translations for different languages. We need reviews from native speakers.

2024-01-08 11:26 UTC, salmjunior commented on home/src/main/resources/rdf/i18n/pt_BR/display/firsttime/search_individuals_vitro.n3
> +:field_label_sort rdfs:label "Campo de classificação de rótulo"@pt-BR .
"Campo de ordenação por rótulo"

2024-01-10 13:14 UTC, bkampe requested changes

2024-01-11 10:20 UTC, litvinovg commented on home/src/main/resources/rdf/i18n/de_DE/display/firsttime/search_individuals_vitro.n3
> +:field_category rdfs:label "KlasseGruppe"@de-DE .
Thank you. Fixed.

2024-01-11 10:21 UTC, litvinovg commented on home/src/main/resources/rdf/i18n/pt_BR/display/firsttime/search_individuals_vitro.n3
> +:field_label_sort rdfs:label "Campo de classificação de rótulo"@pt-BR .
Thank you. Fixed translation.

2024-01-23 16:29 UTC, litvinovg commented
I tested sorting after the discussion at the meeting. It seems to be working.

2024-02-13 09:11 UTC, merged