[Access control] New operator "select query results not contain"
vivo-project/Vitro pull request #432
Opened 2023-12-14 12:30 UTC by litvinovg

# What does this pull request do?

Created operator SPARQL_SELECT_QUERY_RESULTS_NOT_CONTAIN to check if query results do not contain a value.
Renamed operator SPARQL_SELECT_QUERY_CONTAINS to SPARQL_SELECT_QUERY_RESULTS_CONTAIN.
Removed hardcoded variable name "resourceUri", instead add values from all variables returned by query.

# Interested parties
@chenejac @vivo-project/vivo-committers

2023-12-19 08:37 UTC, chenejac requested changes
@litvinovg well done. I have only one tiny comment. Also, I suggest not to add Not start with operation now, we can add that in the separate PR once when it is needed.

2023-12-19 08:37 UTC, chenejac commented on home/src/main/resources/rdf/accessControl/firsttime/operators.n3
> +access-individual:SparqlSelectQueryResultsNotContain a access:Operator;
Please align object names
access-individual:SparqlSelectQueryResultContain

2023-12-19 11:28 UTC, litvinovg commented on home/src/main/resources/rdf/accessControl/firsttime/operators.n3
> +access-individual:SparqlSelectQueryResultsNotContain a access:Operator;
Done

2023-12-19 14:49 UTC, litvinovg commented on home/src/main/resources/rdf/accessControl/firsttime/operators.n3
> +access-individual:SparqlSelectQueryResultsNotContain a access:Operator;
Fixed

2023-12-21 08:48 UTC, chenejac approved these changes
@litvinovg well done.

2023-12-21 08:48 UTC, merged