Replace Qtip Library with Bootstrap Tooltip
vivo-project/Vitro pull request #439
Opened 2024-01-30 20:54 UTC by milospp

**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues)**: (need to be created)

# What does this pull request do?
This pull request focuses on the removal of the Qtip library from the project, substituting it with Bootstrap's tooltip that utilizes Popper 2 as its underlying mechanism. The design has been configured to maintain similarity with the previous implementation using Qtip.

# What's new?
The Bootstrap tooltip automatically identifies available screen space for display but is limited to top, bottom, left, and right orientations, excluding corners.

## Before:
<img width="400" alt="image" src="https://github.com/vivo-project/VIVO/assets/18060127/3f7c3a99-2fbf-4db8-92cf-80ded6f7ce06"> <img width="400" alt="image" src="https://github.com/vivo-project/VIVO/assets/18060127/4678c933-ec17-4247-a0d6-1ec7844691f2"> <img width="400" alt="image" src="https://github.com/vivo-project/VIVO/assets/18060127/a0255b44-435e-4705-82a0-3c3c416778d8"> <img width="400" alt="image" src="https://github.com/vivo-project/VIVO/assets/18060127/80750715-a5b0-4501-90e2-0c6f9f553003">

## After:
<img width="400" alt="Individual" src="https://github.com/vivo-project/VIVO/assets/18060127/165bbd57-71c2-4e2b-8b91-b74926c0ffea"> <img width="400" alt="Search resultd download" src="https://github.com/vivo-project/VIVO/assets/18060127/d2e5c4c3-0a57-4f44-a774-9a9dfdd1dfef"> <img width="400" alt="MapOfScience" src="https://github.com/vivo-project/VIVO/assets/18060127/79a7433c-1b88-47ef-9b9e-c4479f26a563">

# How should this be tested? 
On the Individual profile page:
* Hover, Research area icon <img width="36" alt="image" src="https://github.com/vivo-project/VIVO/assets/18060127/f31872bc-e6a0-47c0-9c15-1c9cda063dcb"> (#researchAreaIcon) 
* Click, Contanct Info link icon <img width="24" alt="image" src="https://github.com/vivo-project/VIVO/assets/18060127/fd0df427-3ff8-41de-9483-9d5a48f90d86"> (#uriIcon)

On the Search results page:
* Click, download icon <img width="29" alt="image" src="https://github.com/vivo-project/VIVO/assets/18060127/39d1cb4e-2f39-4b4f-92e7-79f45d073c07"> (#downloadIcon)

On the MapOfScience page:
* Hover over next elements, #mageIconOne, #exploreInfoIcon, #compareInfoIcon, #imageIconThree

# Additional Notes:
* This pull request may impact dependencies, as it involves the removal of the Qtip library and the addition of Popper. Please be mindful of potential issues in this regard.

# Interested parties
@VIVO-project/vivo-committers

2024-02-07 01:24 UTC, gneissone requested changes
Please see review https://github.com/vivo-project/VIVO/pull/3937#pullrequestreview-1866705358 for general remarks. 

These changes work well with Wilma, but do not work with the default vitro template since vitro does not include bootstrap. Wonder if the tooltips can just be dropped completely in the vitro template, since it was intended to be minimal in the first place...

2025-01-09 13:26 UTC, litvinovg commented on webapp/src/main/webapp/themes/vitro/css/vitroTheme.css
> +.show {
Could you tell me where this css class is used?

2025-01-09 14:28 UTC, litvinovg commented on webapp/src/main/webapp/js/tooltip/tooltip-utils.js
> +        if (!tooltip || document.querySelectorAll('.tooltip').length === 0) {
What is the reason behind this querySelectorAll?

2025-01-09 14:30 UTC, litvinovg commented on webapp/src/main/webapp/js/tooltip/tooltip-utils.js
> +                left: arrowX != null ? `${arrowX}px` : '',
Is empty string a valid value for left and right ?

2025-01-09 14:38 UTC, litvinovg commented on webapp/src/main/webapp/js/tooltip/tooltip-utils.js
> +    innerTooltip.innerHTML = data.title || 'TEST';
Should 'TEST' be there?

2025-01-09 14:39 UTC, litvinovg commented on webapp/src/main/webapp/js/tooltip/tooltip-utils.js
> +            console.log("Cleanup");
Is here on purpose or just left from debugging?

2025-01-23 16:48 UTC, milospp commented on webapp/src/main/webapp/themes/vitro/css/vitroTheme.css
> +.show {
When I tried to upgrade to Bootstrap 5 this was a fix to handle the tabs section. Bootstrap automatically adds "show" class to the tab of the panel that needs to show.
Since the bootstrap 5 upgrade is reverted from this PR, this is actually useless and I will remove it.

2025-01-23 17:32 UTC, milospp commented on webapp/src/main/webapp/js/tooltip/tooltip-utils.js
> +        if (!tooltip || document.querySelectorAll('.tooltip').length === 0) {
This serves as a fallback when the tooltip variable is defined but no tooltip is currently visible on the page; therefore, the condition will allow for displaying a new tooltip.

2025-01-23 18:59 UTC, milospp commented on webapp/src/main/webapp/js/tooltip/tooltip-utils.js
> +                left: arrowX != null ? `${arrowX}px` : '',
Yes, this is the default value for every style attribute in an element. I can also set it to null (which is redefined to an empty string under the hood) if this improves the readability of the code.

2025-01-23 19:00 UTC, milospp commented on webapp/src/main/webapp/js/tooltip/tooltip-utils.js
> +            console.log("Cleanup");
No, this was just for testing purposes. Removed it.

2025-01-23 19:15 UTC, milospp commented on webapp/src/main/webapp/js/tooltip/tooltip-utils.js
> +    innerTooltip.innerHTML = data.title || 'TEST';
I removed this fallback because it will never happen.

2025-01-23 19:21 UTC, milospp commented
> Doesn't work on Vitro for some reason. ![Screenshot at 2025-01-09 15-43-10](https://private-user-images.githubusercontent.com/9299049/401582382-8aae95e3-034e-4814-ac2c-a7672a94f766.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc2NTkxMzYsIm5iZiI6MTczNzY1ODgzNiwicGF0aCI6Ii85Mjk5MDQ5LzQwMTU4MjM4Mi04YWFlOTVlMy0wMzRlLTQ4MTQtYWMyYy1hNzY3MmE5NGY3NjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMjNUMTkwMDM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2UxNDJjNTYxOWM4YzA0YTgzMTJlZWM3ZjZiNzg2MDg2MzE1ZGMzNmJiNTAxNjQ4NWMyMWI1MmZlOGUxY2RkOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.IK01SdMunRFlcVg3NaKTybYaLYSat12SLeZvjGD7gp4)

I couldn't reproduce the same bug, can you please provide more information on when this bug happened?

2025-01-24 08:33 UTC, litvinovg commented
> > Doesn't work on Vitro for some reason. ![Screenshot at 2025-01-09 15-43-10](https://private-user-images.githubusercontent.com/9299049/401582382-8aae95e3-034e-4814-ac2c-a7672a94f766.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc2NTkxMzYsIm5iZiI6MTczNzY1ODgzNiwicGF0aCI6Ii85Mjk5MDQ5LzQwMTU4MjM4Mi04YWFlOTVlMy0wMzRlLTQ4MTQtYWMyYy1hNzY3MmE5NGY3NjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMjNUMTkwMDM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2UxNDJjNTYxOWM4YzA0YTgzMTJlZWM3ZjZiNzg2MDg2MzE1ZGMzNmJiNTAxNjQ4NWMyMWI1MmZlOGUxY2RkOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.IK01SdMunRFlcVg3NaKTybYaLYSat12SLeZvjGD7gp4)
> 
> I couldn't reproduce the same bug, can you please provide more information on when this bug happened?

Sure. Just build Vitro, create any individual, open page profile and notice error in console.

2025-01-24 09:36 UTC, milospp commented on webapp/src/main/webapp/js/tooltip/tooltip-utils.js
> +        if (!tooltip || document.querySelectorAll('.tooltip').length === 0) {
I extracted it to a separate function that is more readable

2025-01-24 09:54 UTC, milospp commented
> > > Doesn't work on Vitro for some reason. ![Screenshot at 2025-01-09 15-43-10](https://private-user-images.githubusercontent.com/9299049/401582382-8aae95e3-034e-4814-ac2c-a7672a94f766.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc2NTkxMzYsIm5iZiI6MTczNzY1ODgzNiwicGF0aCI6Ii85Mjk5MDQ5LzQwMTU4MjM4Mi04YWFlOTVlMy0wMzRlLTQ4MTQtYWMyYy1hNzY3MmE5NGY3NjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMjNUMTkwMDM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2UxNDJjNTYxOWM4YzA0YTgzMTJlZWM3ZjZiNzg2MDg2MzE1ZGMzNmJiNTAxNjQ4NWMyMWI1MmZlOGUxY2RkOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.IK01SdMunRFlcVg3NaKTybYaLYSat12SLeZvjGD7gp4)
> > 
> > 
> > I couldn't reproduce the same bug, can you please provide more information on when this bug happened?
> 
> Sure. Just build Vitro, create any individual, open page profile and notice error in console.

https://youtu.be/X56Hxjf6seI
This is what I got, ignore those two errors, it is related to the LastPass Chrome extension.
Can you confirm whether I reproduced the steps correctly? If yes can you please try again but try to hard reload the page (Ctrl + F5 in Chrome) after building

2025-01-24 10:16 UTC, litvinovg commented
> > > > Doesn't work on Vitro for some reason. ![Screenshot at 2025-01-09 15-43-10](https://private-user-images.githubusercontent.com/9299049/401582382-8aae95e3-034e-4814-ac2c-a7672a94f766.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc2NTkxMzYsIm5iZiI6MTczNzY1ODgzNiwicGF0aCI6Ii85Mjk5MDQ5LzQwMTU4MjM4Mi04YWFlOTVlMy0wMzRlLTQ4MTQtYWMyYy1hNzY3MmE5NGY3NjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMjNUMTkwMDM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2UxNDJjNTYxOWM4YzA0YTgzMTJlZWM3ZjZiNzg2MDg2MzE1ZGMzNmJiNTAxNjQ4NWMyMWI1MmZlOGUxY2RkOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.IK01SdMunRFlcVg3NaKTybYaLYSat12SLeZvjGD7gp4)
> > > 
> > > 
> > > I couldn't reproduce the same bug, can you please provide more information on when this bug happened?
> > 
> > 
> > Sure. Just build Vitro, create any individual, open page profile and notice error in console.
> 
> https://youtu.be/X56Hxjf6seI This is what I got, ignore those two errors, it is related to the LastPass Chrome extension. Can you confirm whether I reproduced the steps correctly? If yes can you please try again but try to hard reload the page (Ctrl + F5 in Chrome) after building

First step is to build Vitro, not VIVO.

2025-01-27 07:19 UTC, litvinovg commented
> > > > > Doesn't work on Vitro for some reason. ![Screenshot at 2025-01-09 15-43-10](https://private-user-images.githubusercontent.com/9299049/401582382-8aae95e3-034e-4814-ac2c-a7672a94f766.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc2NTkxMzYsIm5iZiI6MTczNzY1ODgzNiwicGF0aCI6Ii85Mjk5MDQ5LzQwMTU4MjM4Mi04YWFlOTVlMy0wMzRlLTQ4MTQtYWMyYy1hNzY3MmE5NGY3NjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMjNUMTkwMDM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2UxNDJjNTYxOWM4YzA0YTgzMTJlZWM3ZjZiNzg2MDg2MzE1ZGMzNmJiNTAxNjQ4NWMyMWI1MmZlOGUxY2RkOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.IK01SdMunRFlcVg3NaKTybYaLYSat12SLeZvjGD7gp4)
> > > > 
> > > > 
> > > > I couldn't reproduce the same bug, can you please provide more information on when this bug happened?
> > > 
> > > 
> > > Sure. Just build Vitro, create any individual, open page profile and notice error in console.
> > 
> > 
> > https://youtu.be/X56Hxjf6seI This is what I got, ignore those two errors, it is related to the LastPass Chrome extension. Can you confirm whether I reproduced the steps correctly? If yes can you please try again but try to hard reload the page (Ctrl + F5 in Chrome) after building
> 
> First step is to build Vitro, not VIVO.

@milospp Did you manage to reproduce the issue?
You were building and deploying VIVO with Vitro theme, instead build and install Vitro application.

2025-01-28 14:21 UTC, milospp commented
> d deploying VIVO with Vitro theme, instead build and install Vitro application.

Yes, I reproduced it. I just didn't work on it until now. I updated the code. Can you check it out now?

2025-01-30 08:35 UTC, litvinovg commented
I don't think the tip is supposed to appear in that place 
![grafik](https://github.com/user-attachments/assets/5ccb2ea7-88d6-45fc-bc26-025f38985c7d)

2025-02-14 13:45 UTC, milospp commented
> I don't think the tip is supposed to appear in that place ![grafik](https://private-user-images.githubusercontent.com/9299049/408046507-5ccb2ea7-88d6-45fc-bc26-025f38985c7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzk1NDEwMDMsIm5iZiI6MTczOTU0MDcwMywicGF0aCI6Ii85Mjk5MDQ5LzQwODA0NjUwNy01Y2NiMmVhNy04OGQ2LTQ1ZmMtYmMyNi0wMjVmMzg5ODVjN2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAyMTRUMTM0NTAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmRlZDYwMTE2N2I2MDQwNTk4Yjg4NzE0OGVjMzg1NjM1ZDFhMTY5ODQ2OTY1OTQ2Y2UzZDhkZGIyMGRmYzc3OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.yVuKV9rdIuOaLr1YRG1OGM9ds1J1E2pcE4j2loXLGzs)

Fixed

2025-03-03 12:51 UTC, litvinovg approved these changes
Looks good to me.

2025-03-19 16:04 UTC, gneissone approved these changes
Working well, thanks.

2025-03-20 10:56 UTC, merged