Custom context path configuation option
vivo-project/Vitro pull request #475
Opened 2024-09-27 06:09 UTC by litvinovg

**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues/3846)**: (please link to issue)

# What does this pull request do?
These new configuration options allow you to create correct links when the application is behind a proxy server, thus minimizing the required redirects.

# What's new?
Added configuration option to modify context path in case when the application is behind proxy. 
Replaced calls for context path to utility methods that allow overriding default context path.

# How should this be tested?
Default behavior when configuration property is not set should be the same.
To test application behind proxy one would need to configure webserver and tomcat in proxy mode like described in workaround of linked issue.
* General navigation between application pages
* Authorization
* Edit this individual page should work the same

Example:
This change require documentation to be updated.

# Interested parties
@VIVO-project/vivo-committers

# Reviewers' expertise
Candidates for reviewing this PR should have some of the following expertises:
1. Java

# Reviewers' report template
## General comment
A reviewer should provide here comments and suggestions for requested changes if any.
## Testing
A reviewer should briefly describe here how it was tested
## Code reviewing
A reviewer should briefly describe here which part was code reviewed

2024-10-28 11:45 UTC, chenejac requested changes
@litvinovg I have left two tiny comments. Please, also invest whether [edu/cornell/mannlib/vitro/webapp/filters/PageRoutingFilter.java](https://github.com/vivo-project/Vitro/blob/main/api/src/main/java/edu/cornell/mannlib/vitro/webapp/filters/PageRoutingFilter.java#L67) should be updated as well.

2024-10-28 11:45 UTC, chenejac commented on api/src/main/java/edu/cornell/mannlib/vitro/webapp/controller/freemarker/ContactFormController.java
> +import edu.cornell.mannlib.vitro.webapp.config.ConfigurationProperties;
probably not needed

2024-10-28 11:45 UTC, chenejac commented on api/src/main/java/edu/cornell/mannlib/vitro/webapp/freemarker/config/FreemarkerConfigurationImpl.java
> +import edu.cornell.mannlib.vitro.webapp.config.ConfigurationProperties;
probably not needed

2024-10-28 14:06 UTC, litvinovg commented on api/src/main/java/edu/cornell/mannlib/vitro/webapp/controller/freemarker/ContactFormController.java
> +import edu.cornell.mannlib.vitro.webapp.config.ConfigurationProperties;
Yes. Removed.

2024-10-28 14:06 UTC, litvinovg commented on api/src/main/java/edu/cornell/mannlib/vitro/webapp/freemarker/config/FreemarkerConfigurationImpl.java
> +import edu.cornell.mannlib.vitro.webapp.config.ConfigurationProperties;
Yes. Removed.

2024-10-28 14:08 UTC, litvinovg commented
> @litvinovg I have left two tiny comments. Please, also invest whether [edu/cornell/mannlib/vitro/webapp/filters/PageRoutingFilter.java](https://github.com/vivo-project/Vitro/blob/main/api/src/main/java/edu/cornell/mannlib/vitro/webapp/filters/PageRoutingFilter.java#L67) should be updated as well.
I think PageRoutingFilter shouldn't be changed.

2024-10-29 07:56 UTC, chenejac submitted a review, later dismissed
@litvinovg thanks. Well done.

2025-04-23 09:18 UTC, litvinovg commented
Resolved merge conflicts, rebased on top of main branch

2025-07-17 19:05 UTC, brianjlowe commented on api/src/main/java/edu/cornell/mannlib/vitro/webapp/controller/freemarker/FreemarkerHttpServlet.java
> +        String url = vreq.getRequestURI().substring(ContextPath.getPath(vreq).length());
This doesn't seem to work as intended, if I'm understanding the intent correctly.  If I set context.path=apricot but deploy the application to webapps/vitro/, then requesting the application at localhost:8080/vitro gives the following error:

```
java.lang.StringIndexOutOfBoundsException: begin 7, end 6, length 6
	...
	java.lang.String.substring(String.java:2682)
	edu.cornell.mannlib.vitro.webapp.controller.freemarker.FreemarkerHttpServlet.getDisplayModelMenu(FreemarkerHttpServlet.java:491)
```
	
This error makes sense, since it's trying to remove the rewritten context name for links ("apricot") from the shorter "vitro" that is actually coming in to Tomcat.

It's not immediately obvious to me whether the original ```.substring(vreq.getContextPath().length());``` can simply be restored here and have the desired functionality work correctly, or whether something else needs to happen.

2025-07-31 10:42 UTC, litvinovg commented on api/src/main/java/edu/cornell/mannlib/vitro/webapp/controller/freemarker/FreemarkerHttpServlet.java
> +        String url = vreq.getRequestURI().substring(ContextPath.getPath(vreq).length());
Thank you for catching this!
I have changed configuration property so that it would take boolean parameter in case application context name should be excluded from links as a less error-prone approach. I also renamed configuration property to context.path.exclude to better define it's purpose and updated comment in example.runtime.properties.
Please have a look when you have time.

2025-08-05 17:02 UTC, brianjlowe requested changes
Have tested the various functionality when reverse-proxying the root path to the /vivo/ context in Tomcat. Everything works fine, and this is a very useful feature. I made just some very tiny suggested tweaks to the example.runtime.properties.

2025-08-05 17:02 UTC, brianjlowe commented on home/src/main/resources/config/example.runtime.properties
> +# To exclude tomcat application context name from generated links uncomment following line.
I would leave a blank line (without #) before the next property starts on line 29, which would match the corresponding file in VIVO. I would also suggest a small edit to "To exclude _the_ Tomcat [capitalized]..." and putting a period after "Default value is false."

2025-08-05 17:05 UTC, brianjlowe commented on api/src/main/java/edu/cornell/mannlib/vitro/webapp/controller/freemarker/FreemarkerHttpServlet.java
> +        String url = vreq.getRequestURI().substring(ContextPath.getPath(vreq).length());
Very nice solution. All fine now.

2025-08-06 09:28 UTC, litvinovg commented on home/src/main/resources/config/example.runtime.properties
> +# To exclude tomcat application context name from generated links uncomment following line.
I corrected the text.

2025-08-06 19:52 UTC, brianjlowe approved these changes

2025-08-09 09:41 UTC, merged